"""Constants of Metadrive game"""

# TODO : All capital leters ?

DEBUG = False

# Main loop tick rate
TICK_RATE = 30  # 30 tick per seconds

# Default window size
SCREEN_HEIGHT_DEFAULT = 1920  # 640
SCREEN_WIDTH_DEFAULT = 1080  # 640

# Controls
TEST_DANCEPAD = False

# Defaults
UP_ARROW = 2
LEFT_ARROW = 0
DOWN_ARROW = 3
RIGHT_ARROW = 1

# Chinese dancepad
if TEST_DANCEPAD:
    DOWN_ARROW = 1
    RIGHT_ARROW = 3

# Parameters
INACTIVITY_TIME_IN_MENU = 30000  # in ms
INACTIVITY_TIME_IN_GAME = 10000  # in ms
FULLSCREEN = False

# Icon and window title
ICON_IMAGE = "images/"
WINDOW_TITLE = "Metadrive"

# Colors
ABLACK = (0, 0, 0, 200)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
AWHITE = (255, 255, 255, 70)
PINK = (235, 62, 149)  # (255, 72, 220)
MENU_BLUE = (33, 183, 224)

# Speed
MIN_KEY_SPEED = 0
MAX_KEY_SPEED = 8

MIN_IMAGE_SPEED = 0.3
MAX_IMAGE_SPEED = 16

# HUD

# Speedometer
SPEEDOMETER_CENTER_X = 200
SPEEDOMETER_CENTER_Y = 600  # 600
SPEEDOMETER_RADIUS = 150
SPEEDOMETER_EXTERN_RADIUS = int(SPEEDOMETER_RADIUS * 1.1)

SPEEDOMETER_MAIN_NEEDLE_LENGHT = int(SPEEDOMETER_RADIUS * 0.75)
SPEEDOMETER_FUTURE_NEEDLE_LENGHT = int(SPEEDOMETER_RADIUS * 0.5)
SPEEDOMETER_NEEDLE_SEMIWIDTH = 2
SPEEDOMETER_GLOBAL_ANGLE = 260

SPEEDOMETER_NUMBER_OF_MARKS = 9
SPEEDOMETER_INNER_RADIUS_MARKS = int(SPEEDOMETER_RADIUS * 0.9)
SPEEDOMETER_OUTER_RADIUS_MARKS = int(SPEEDOMETER_RADIUS * 1.1)

SPEEDOMETER_CENTER_CIRCLE_RADIUS = 10

# Clues
CLUE_INDICATION_TOP = 300
CLUE_RANGE_MIN = 6./8  # Start Percent of speedometer global angle
CLUE_RANGE_MAX = 1.0  # End Percent of speedometer global angle
CLUE_RADIUS = int(SPEEDOMETER_RADIUS * 0.9)

SUBTITLE_TEXT_TOP = 1200
SUBTITLE_MIN_DURATION = 2
SUBTITLE_DURATION_BY_CHAR = 0.1

# Transition
TRANSITION_OPACITY_DELTA = 10
